**Important**: You must click the "Save" / "Check me" button on **every** question below; otherwise, *your response will not be saved*.

.. |role| replace:: In the following questions, briefly describe the role each team member has played in all aspects of this course. A failure to provide details about team and content preparation roles will not earn full credit for this assignment.

.. |communication and cooperation| replace:: Has your group communicated clearly and cooperated successfully? If any group members seem to take charge of all assignments or group members seem uninterested and overly passive in group discussions, detail those issues.

.. |reliability and participation| replace:: Discuss the reliability and participation of your group members. Has anyone missed a meeting, shown up late, left early, or missed any internal deadlines? If so, please be specific.

.. |contributions| replace:: Evaluate each team member’s contribution to all aspects of this course by distributing an assignment’s total possible points (100) as you think they should be allocated based on each member’s input. Please note that you are not rating each member on a scale of 0 to 100; rather, you are distributing a total of 100 points across all team members other than yourself (e.g., if everyone has contributed equally on a four-person team, you should give your three team members each a 33.3; if everyone has contributed equally on a five-person team, you should give your four team members each a 25). This rating does not count toward individual grades; rather, it is an opportunity to reveal any problems that might exist within your group. **To aid in transparency, I will make your anonymous ratings available to the entire team.**

.. |correct value| replace:: Please enter a value between 0 and 100 for each team member. The total of all values should sum to 100.

.. |unequal distribution| replace:: REQUIRED: If the allocated points above are not equally distributed, you must provide an explanation for your ratings.

.. |help| replace:: Based on any of your answers at this point, please let me know how I can best help your group going forward (meeting with your entire group, meeting with just you, monitoring specific group member contributions/team deadlines, applying a different grading scale, no intervention). Please add any other information that I should know.

.. |fair| replace:: Throughout the semester, have communication, workload, and participation seemed equal and fair? Detail any issues.

.. |interaction and performance| replace:: Please offer any additional information you’d like me to know about your group’s interaction and performance throughout the semester.