**Important**: You must click the "Save" / "Check me" button on **every** question below; otherwise, *your response will not be saved*.


.. |pre role| replace:: In the following questions, briefly describe the role each team member has played in

.. |post role| replace:: A failure to provide details about team and content preparation roles will not earn full credit for this assignment.

.. |role 1| replace:: |pre role| the project idea selection, project proposal, and mid-project review aspects of Introduction to Design II (ECE 1022). |post role|

.. |role 2| replace:: |pre role| the project prototype development, both hardware and software, aspects of Introduction to Design II (ECE 1022). |post role|

.. |role 3| replace:: |pre role| the project prototype development, venture capital presentation, and final-project review aspects of Introduction to Design II (ECE 1022). |post role|


.. |communication and cooperation| replace:: Has your group communicated clearly and cooperated successfully? If any group members seem to take charge of all assignments or group members seem uninterested and overly passive in group discussions, detail those concerns.

.. |reliability and participation| replace:: Discuss the reliability and participation of your group members. Has anyone missed a meeting, shown up late, left early, or missed any internal deadlines? If so, please be specific.


.. |pre contributions| replace:: Evaluate each team member’s contribution to the

.. |post contributions| replace:: by distributing the assignment’s total possible points (100) as you think they should be allocated based on each member’s input. Please note that you are not rating each member on a scale of 0 to 100; rather, you are distributing a total of 100 points across all team members other than yourself (e.g., if everyone has contributed equally on a four-person team, you should give your three team members each a 33.3; if everyone has contributed equally on a five-person team, you should give your four team members each a 25). This rating does not count toward individual grades; rather, it is an opportunity to reveal any problems that might exist within your group. **To aid in transparency, I will make your anonymous ratings available to the entire team.**

.. |contributions 1a| replace:: |pre contributions| **idea development and project proposal** |post contributions|

.. |contributions 2a| replace:: |pre contributions| **prototype development and project progress thus far** |post contributions|

.. |contributions 3a| replace:: |pre contributions| **prototype development and project completion** |post contributions|


.. |pre contributions repeat| replace:: Repeat the question above, this time evaluating each team member’s contribution to the

.. |contributions 1b| replace:: |pre contributions repeat| **Mid-Project Review presentation**.

.. |contributions 3b| replace:: |pre contributions repeat| **Final-Project Review presentation**.


.. |correct value| replace:: Please enter a value between 0 and 100 for each team member. The total of all values should sum to 100.

.. |unequal distribution| replace:: REQUIRED: If the allocated points above are not equally distributed, you must provide an explanation for your ratings. You may send screenshots of group messages or other documentation directly to your instructor via Canvas messaging, but do describe those artifacts here.

.. |help| replace:: Based on any of your answers at this point, please let me know how I can best help your group going forward (meeting with your entire group, meeting with just you, monitoring specific group member contributions/team deadlines, applying a different grading scale, no intervention). Please add any other information that I should know.
